### ISSUE TITLE
把编码从Ascii改成utf-8就可以解决玩家名字乱码的问题了

### ISSUE THREAD

**Issue by KirosHan** [LiuOcean/PalRconCli#1]
把编码从Ascii改成utf-8就可以解决玩家名字乱码的问题了

**Comment by LiuOcean** [comment]
我看 rcon 的标准是 ASCII，但是帕鲁的服务器没完全遵守这个。发的消息还是得用 ASCII。_(:з」∠)_ 空了我改一下

**Comment by KirosHan** [comment]
是的，官方的服务端很混乱，不知道具体什么编码就是发送不了中文，基本上同时支持日文和中文的编码我都试了一遍
